# Generated by Django 2.2.1 on 2019-07-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0014_populate_licenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short', models.CharField(max_length=255)),
                ('repeatable', models.BooleanField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('transmit_id', models.CharField(max_length=255)),
                ('classification_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit.ClassificationSystem')),
            ],
        ),
    ]
