#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
# Taken from https://gist.github.com/ndarville/3625246

language: python


python:
  - 2.7

sudo: false

addons:
    postgresql: "9.4"
    apt:
       sources:
       - elasticsearch-2.x
       packages:
       - elasticsearch=2.4.5
       - python-requests
       - python-lxml
       - curl
       - libffi-dev
       - libssl-dev
       - ghostscript

services:
  - postgresql
  - redis
  - elasticsearch


env:
  global:
      # RoMEO API key
    - secure: "hQg8tso/Qv4zXhP4A2ahKKhFZQSariIvUr+xqzzoTVtuN/9OuzBFjZ1UF8atM5KKGZ47fFMK2wTjbVOWjSyLH/SF3Wy8bX9oHHg1P8bXcsle6O/tfa3U/2s0UiYtThEdxp+iyQIr6cjBA0gmB0v/vFrQot91GvjlUbi70Xjfcts="
      # Zenodo Sandbox API key
    - secure: "KjRrTKrNyhv1xVl2UBtJ/qH0uFGItvxw7/pGFfPrcwxD5YAB5daePDaIGe/tlVy+lrQi0D9x1CA8MB2vm+Lf4jrfO+3ZHCkmb4ecbumPV7DxEbgFsralBx65PRRVUiDW1Oy0RyigxXNNdtNLvTVr1PYrZYD407HZnP6LrJP0ONM="
      # Gitbot l10n key (for translation notifications)
    - secure: "qm+WAH7GpYIjid+q5tVnRgpiIwRmo7C8ou8GAeHJwTxkcmX8+YsYhuuacXO5mW/gcvjb9UNVCDkIKqjIsxJdmC0JovXJJ2dG2g1P39FfOCsF1+FpOqxdjBxdlJCoPb+Wmx7qk5+n+ZgqArgDPFwTWAPqsfshVPLplvaIYfA6H2s="


virtualenv:
  system_site_packages: true

before_install:
  - export DJANGO_SETTINGS_MODULE=dissemin.settings
  - export PYTHONPATH=$HOME/builds/wetneb/dissemin
  - export PIP_USE_MIRRORS=true
  - echo "from .travis import *" > dissemin/settings/__init__.py
  - cp dissemin/settings/secret_template.py dissemin/settings/secret.py

install:
  - pip install setuptools --upgrade
  - pip install psycopg2 --quiet
  - pip install -r requirements.txt
  - pip install codacy-coverage coverage coveralls
  - pip install pyflakes
  - ./pyflakes.sh
  - pip freeze

before_script:
  - psql --version
  - psql -c "CREATE DATABASE dissemin;" -U postgres

script:
  - coverage run --source=dissemin,papers,backend,deposit,upload,statistics --omit=*/migrations/*,dissemin/settings/* manage.py test -v 2

after_success:
  - coveralls

notifications:
  irc:
    channels:
      - "ulminfo.fr#dissemin"
    on_success: never
    on_failure: never
